$kind: http-example
id: c87851c1-f2e7-5794-96a8-e9688fd1fa85
request:
  url: "{{base_url}}/zones/{{zone_id}}/access/apps/{{app_id}}"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
