$kind: http-example
id: 1ad0226c-fd5c-55a2-b1b1-9b90c8f96b14
name: Create Deployment response failure.
request:
  url: "{{base_url}}/accounts/{{account_id}}/workers/scripts/{{script_name}}/deployments"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  queryParams:
    - key: force
      value: "true"
      disabled: true
      description: If set to true, the deployment will be created even if normally blocked by something such rolling back to an older version when a secret has changed.
  body:
    type: json
    content: |-
      {
        "strategy": "percentage",
        "versions": [
          {
            "version_id": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "percentage": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            }
          },
          {
            "version_id": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "percentage": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            }
          }
        ],
        "annotations": {
          "workers/message": "Deploy bug fix."
        }
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
