$kind: http-example
id: 33c056bd-4c5b-5786-aea3-1d9ff3f71664
name: List Spectrum application protocols response failure.
request:
  url: "{{base_url}}/zones/{{zone_id}}/spectrum/protocols"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
