$kind: http-example
id: 70ee85c7-3efe-54c3-b187-10221f5932bb
name: Patch Argo Smart Routing enablement setting failure.
request:
  url: "{{base_url}}/zones/{{zone_id}}/argo/smart_routing"
  method: PATCH
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "value": "on"
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 2000
