$kind: http-example
id: fb8f3f23-0c86-5da0-a082-76730044b20e
request:
  url: "{{base_url}}/accounts/{{account_id}}/mnm/config"
  method: PATCH
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      {
        "default_sampling": 1,
        "name": "cloudflare user's account"
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
