$kind: http-example
id: 21d9b8b8-86e5-54a0-afd9-7bf1ca2c7870
request:
  url: "{{base_url}}/zones/{{zone_id}}/waiting_rooms/settings"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "search_engine_crawler_bypass": true
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "search_engine_crawler_bypass": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        }
      }
order: 1000
