$kind: http-example
id: ea7b3681-79ba-53e6-9eb1-43f7d98ab56b
request:
  url: "{{base_url}}/accounts/{{account_id}}/roles/{{role_id}}"
  method: GET
  headers:
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
