$kind: http-example
id: 5d8a514f-97ac-5bf5-a6cb-68ee90b41fd9
name: Create predefined profile response.
request:
  url: "{{base_url}}/accounts/{{account_id}}/dlp/profiles/predefined/{{profile_id}}/config"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      {
        "ai_context_enabled": false,
        "allowed_match_count": 5,
        "confidence_threshold": "low",
        "enabled_entries": [
          "05605aa3-27e7-8ca4-70c4-e6203427f9bb",
          "32600971-5a7b-6c85-3507-cab553c22201"
        ],
        "entries": [
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          },
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        ],
        "ocr_enabled": false
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
