$kind: http-example
id: bdc0db31-9274-5bd0-80c5-fdd16de9943f
request:
  url: "{{base_url}}/zones/{{zone_id}}/api_gateway/settings/schema_validation"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      {
        "validation_default_mitigation_action": "block",
        "validation_override_mitigation_action": "none"
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "validation_default_mitigation_action": "block",
        "validation_override_mitigation_action": null
      }
order: 1000
