$kind: http-example
id: afabd7ec-2aa1-517e-8281-d3483c03ea2c
request:
  url: "{{base_url}}/zones/{{zone_id}}/access/apps"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": [
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          },
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        ]
      }
order: 1000
