$kind: http-example
id: c31c5b6e-32ed-5358-9034-3b0ec45695d2
request:
  url: "{{base_url}}/zones/{{zone_id}}/pagerules/settings"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
