$kind: http-example
id: 28ae222a-913a-5915-bd7a-7f1350221b62
request:
  url: "{{base_url}}/accounts/{{account_id}}/warp_connector/{{tunnel_id}}/configurations"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
