$kind: http-example
id: 87e1be54-9ebb-565a-b4d1-f22f2193d64b
name: Edit Keyless SSL Configuration response.
request:
  url: "{{base_url}}/zones/{{zone_id}}/keyless_certificates/{{keyless_certificate_id}}"
  method: PATCH
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "enabled": false,
        "host": "example.com",
        "name": "example.com Keyless SSL",
        "port": 24008,
        "tunnel": {
          "private_ip": "10.0.0.1",
          "vnet_id": "7365377a-85a4-4390-9480-531ef7dc7a3c"
        }
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
