$kind: http-example
id: 81bdb6ff-b64e-5d8b-8c43-57ffa21f648b
request:
  url: "{{base_url}}/zones/{{zone_id}}/token_validation/config/{{config_id}}"
  method: PATCH
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "description": "Long description for Token Validation Configuration",
        "title": "Example Token Validation Configuration",
        "token_sources": [
          "http.request.headers[\"x-auth\"][0]",
          "http.request.cookies[\"Authorization\"][0]"
        ]
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
