$kind: http-example
id: 41552f46-eb9e-526f-a4b7-6a61600c75d8
name: Read Configuration failure.
request:
  url: "{{base_url}}/accounts/{{account_id}}/event_notifications/r2/{{bucket_name}}/configuration/queues/{{queue_id}}"
  method: GET
  headers:
    - key: cf-r2-jurisdiction
      value: default
      description: Jurisdiction where objects in this bucket are guaranteed to be stored.
    - key: Accept
      value: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          },
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        ],
        "messages": [
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          },
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        ],
        "result": null
      }
order: 3000
