$kind: http-example
id: 78f18fe3-519a-5a4b-91f5-d36e45d3eb5d
request:
  url: "{{base_url}}/zones/{{zone_id}}/access/apps"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: "{}"
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
