$kind: http-example
id: fdf0cbe8-e83c-5bb1-97e1-2be663552b81
name: Ingress created.
request:
  url: "{{base_url}}/zones/{{zone_id}}/intel/sinkholes/{{sinkhole_id}}/ingresses"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      {
        "cidr": "string"
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    - key: Location
      value: string
      description: URI of the created ingress.
    - key: Content-Type
      value: application/json
  body:
    type: json
    content: |-
      {
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
