$kind: http-example
id: 79a0f74d-b3d5-533a-a4e3-072b98ee1d0e
name: Set the Local Domain Fallback list for a device settings profile response failure.
request:
  url: "{{base_url}}/accounts/{{account_id}}/devices/policy/{{policy_id}}/fallback_domains"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      [
        {
          "suffix": "example.com"
        },
        {
          "suffix": "example.com"
        }
      ]
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 2000
