$kind: http-example
id: f2e1be2f-58f9-50c3-8369-339b4cb0ce75
request:
  url: "{{base_url}}/zones/{{zone_id}}/fraud_detection/settings"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
