$kind: http-example
id: bf477952-cb65-50e6-96b9-b2f97e7aaf77
request:
  url: "{{base_url}}/zones/{{zone_id}}/email/routing"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
