$kind: http-example
id: 9a50cd34-69ca-5e6d-af8f-f0d3a9265139
request:
  url: "{{base_url}}/zones/{{zone_id}}/email/routing"
  method: GET
  headers:
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
