$kind: http-example
id: 4995d812-1cc9-55e8-a108-122bfd4fc637
name: Response body when an Application is not found.
request:
  url: "{{base_url}}/accounts/{{account_id}}/containers/applications/{{application_id}}"
  method: DELETE
  headers:
    Accept: application/json
response:
  statusCode: 404
  statusText: Not Found
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": true,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 3000
