$kind: http-example
id: 3d241b43-8f15-54c6-840a-dc1f327d0a26
request:
  url: "{{base_url}}/zones/{{zone_id}}/token_validation/config/{{config_id}}"
  method: DELETE
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
