$kind: http-example
id: 0e4cdd90-5d24-502d-9a59-e7337dfbf417
name: Unknown extractor type or no rules configured.
request:
  url: "{{base_url}}/accounts/{{account_id}}/field_extractors/{{extractor}}"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 404
  statusText: Not Found
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          },
          {
            "value": "<Error: Too many levels of nesting to fake this schema>"
          }
        ],
        "messages": [
          {
            "code": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "message": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            }
          },
          {
            "code": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "message": {
              "value": "<Error: Too many levels of nesting to fake this schema>"
            }
          }
        ],
        "result": {}
      }
order: 2000
