$kind: http-example
id: 0d10fb1f-4b3f-5297-bf83-147b65e24cba
request:
  url: "{{base_url}}/zones/{{zone_id}}/settings"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": {}
      }
order: 2000
