$kind: http-example
id: 6c4b487d-74cd-5dfa-a1bd-ea7e6d1ca1ea
name: Get Transformations configuration response failure.
request:
  url: "{{base_url}}/zones/{{zone_id}}/settings/transformations_config"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": {}
      }
order: 2000
