$kind: http-example
id: 4966e771-d2a5-519e-b8df-07448e5ceac9
name: List Scan Configs failure.
request:
  url: "{{base_url}}/accounts/{{account_id}}/cloudforce-one/scans/config"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": {
          "code": 10433,
          "message": "request error"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 2000
