$kind: http-example
id: de3b0e8c-5ad7-5bdd-a5f8-07e6ef39d201
name: Authentication error or missing zone email routing settings update permission.
request:
  url: "{{base_url}}/zones/{{zone_id}}/email/routing/dns"
  method: DELETE
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "name": "example.net"
      }
response:
  statusCode: 403
  statusText: Forbidden
  headers:
    Content-Type: text/plain
  body:
    type: text
    content: ""
order: 2000
