$kind: http-example
id: 11d9612a-092a-5f71-b106-3e90d8ed63ee
name: Authentication error or missing zone email routing settings update permission.
request:
  url: "{{base_url}}/zones/{{zone_id}}/email/routing/dns"
  method: DELETE
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "name": "example.net"
      }
response:
  statusCode: 403
  statusText: Forbidden
  headers:
    Content-Type: text/plain
  body:
    type: text
    content: ""
order: 2000
