$kind: http-example
id: 0140dfc2-e21a-5f86-8061-f952f259480c
name: Create an Access application policy response.
request:
  url: "{{base_url}}/accounts/{{account_id}}/access/apps/{{app_id}}/policies"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "name": "Allow devs",
        "decision": "allow",
        "include": []
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
