$kind: http-example
id: b0dbd440-ef8f-5c2d-977a-253e4be73789
name: Get the application response.
request:
  url: "{{base_url}}/accounts/{{account_id}}/resource-library/applications/{{id}}"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
