$kind: http-example
id: 835a1ae7-421c-5b71-8323-3856d6a2ba33
request:
  url: "{{base_url}}/zones/{{zone_id}}/page_shield"
  method: GET
  headers:
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [],
        "result": null
      }
order: 2000
