$kind: http-example
id: cfdc5b16-6ab7-5255-8453-d66975377de5
request:
  url: "{{base_url}}/zones/{{zone_id}}/page_shield"
  method: GET
  headers:
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
