$kind: http-example
id: e71ec3cf-f7b6-5670-a6bd-8831315bb9b2
name: Logging settings update response.
request:
  url: "{{base_url}}/accounts/{{account_id}}/gateway/logging"
  method: PUT
  headers:
    Content-Type: application/json
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
  body:
    type: json
    content: |-
      {
        "redact_pii": true
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
