$kind: http-example
id: 78479754-e2d3-57a6-8372-063f0162cea3
request:
  url: "{{base_url}}/zones/{{zone_id}}/access/certificates/settings"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
