$kind: http-example
id: e69aceb4-31da-5578-ba3e-965c77bbe212
name: Zero Trust account configuration response.
request:
  url: "{{base_url}}/accounts/{{account_id}}/gateway/configuration/custom_certificate"
  method: GET
  headers:
    Accept: application/json
    X-Auth-Email: "{{api_email}}"
    X-Auth-Key: "{{api_key}}"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "enabled": true,
        "binding_status": "pending_deployment",
        "id": "d1b364c5-1311-466e-a194-f0e943e0799f",
        "updated_at": "1987-04-08T05:11:46.614Z"
      }
order: 1000
