$kind: http-example
id: 48a15345-166f-5ee1-8259-94722ac2e811
name: A newly created application.
request:
  url: "{{base_url}}/accounts/{{account_id}}/containers/applications"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "name": "string",
        "scheduling_policy": "default",
        "instances": 0,
        "max_instances": 0,
        "configuration": {
          "image": "string"
        },
        "durable_objects": {
          "namespace_id": "14758f1afd44c09b7992073ccf00b43d"
        }
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "errors": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "messages": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "result": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "success": {
          "value": "<Error: Too many levels of nesting to fake this schema>"
        }
      }
order: 1000
