$kind: http-example
id: 940c7a37-0ecf-5cb3-942b-2d928e330ba2
name: Could not create the application because of input/limits reasons, more details in the error code.
request:
  url: "{{base_url}}/accounts/{{account_id}}/containers/applications"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "name": "{{name}}",
        "scheduling_policy": "default",
        "instances": 0,
        "max_instances": 0,
        "configuration": {
          "image": "{{configuration__image}}"
        }
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": true,
        "errors": [
          {
            "code": 7003,
            "message": "No route for the URI"
          }
        ],
        "messages": [],
        "result": null
      }
order: 2000
